### ISSUE TITLE
t/compress-level.t flaky with different zlib implementations

### ISSUE THREAD

**Issue by pghmcfc** [benkasminbullock/image-png-libpng#40]
The test is looking for specific numbers of bytes and might not get the same results with different `zlib` implementations. For example, I see this after switching from `zlib` to `zlib-ng` (in `zlib` compatibility mode):
```
$ make test
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Libpng.bs blib/arch/auto/Image/PNG/Libpng/Libpng.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/bKGD.t .............. ok
t/bogus.t ............. skipped: libpng version is 1.6.40
t/chrm-xyz.t .......... ok
t/cHRM.t .............. ok
t/chunk-cache-max.t ... ok
t/chunk-malloc-max.t .. ok
t/comp-buff.t ......... ok
#   Failed test 'source /builddir/build/BUILD/Image-PNG-Libpng-0.57/t/libpng/z03n2c08.png (level: 3, 232 bytes) equal to target (level: 3, 231 bytes)'
#   at t/compress-level.t line 46.
#          got: 232
#     expected: 231
# Looks like you failed 1 test of 27.
t/compress-level.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/27 subtests 
t/Const.t ............. ok
t/copy-all-png.t ...... ok
t/daft.t .............. ok
t/exif.t .............. ok
t/functions.t ......... ok
t/gAMA.t .............. ok
t/get-internals.t ..... ok
t/get-palette-max.t ... ok
t/get-text.t .......... ok
t/header.t ............ ok
t/hIST.t .............. ok
t/io-read.t ........... ok
t/io.t ................ ok
t/Libpng.t ............ ok
t/oFFs.t .............. ok
t/pCAL.t .............. ok
t/pHYs.t .............. ok
t/PLTE.t .............. ok
t/read-from-scalar.t .. ok
t/sBIT.t .............. ok
t/sCAL.t .............. ok
t/set-itxt.t .......... ok
t/set-text.t .......... ok
t/split-alpha.t ....... ok
t/sPLT.t .............. ok
t/supports.t .......... ok
t/tIME.t .............. ok
t/transformations.t ... ok
t/tRNS.t .............. ok
t/user-limits.t ....... ok
Test Summary Report
-------------------
t/compress-level.t  (Wstat: 256 (exited 1) Tests: 27 Failed: 1)
  Failed test:  8
  Non-zero exit status: 1
Files=38, Tests=399,  3 wallclock secs ( 0.10 usr  0.06 sys +  2.12 cusr  0.48 csys =  2.76 CPU)
Result: FAIL
Failed 1/38 test programs. 1/399 subtests failed.
make: *** [Makefile:973: test_dynamic] Error 255
```
Perhaps the test could be a little more flexible about what it accepts?

**Comment by benkasminbullock** [comment]
This is a specific test of the compression levels being applied correctly
which relies on getting the correct Zlib compression levels. It would be
better to turn off the test in the case of a non-Zlib compression library
being used rather than try to think of alternatives. So we would have to
enquire to libpng what compression library was being used and then skip the
tests if it was not actually Zlib. I'll have to look up if there is a way
to check the underlying compression library in libpng. I can't think of any
offhand. It should be safe to install the module regardless of this test
failure.

**Comment by benkasminbullock** [comment]
zlib-ng seems to set ZLIB_VERSION to a string which distinguishes it from the standard zlib, but after checking the source code for libpng, there is no access to the zlib version string ZLIB_VERSION via libpng, only VERNUM, a numerical version of it. We need to have a way to find out that it is zlib-ng to turn off the test.

**Comment by benkasminbullock** [comment]
Provisionally I've switched off the test which relies on an exact match of sizes but kept the basic compression level tests which should work with zlib-ng. This is now on CPAN as

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.57_01

Please test it with zlib-ng versions of libpng to see if the tests pass correctly.

**Comment by pghmcfc** [comment]
I tried 0.57_01 on the Fedora Linux development branch (which is where this problem showed up for me) and it built successfully on the following architectures: i686, ppc64le, s390x, aarch64, x86_64.

I see that only the "equal size" test has been disabled; I could envision cases in which the "smaller" or "bigger" tests might also fail (e.g. some new implementation might take advantage of hardware compression support so that even on low compression settings there was a very small result). However, for the time being, the immediate problem is solved - thanks.

**Comment by benkasminbullock** [comment]
The tests both allow for equality, so if those tests stop working with the zlib-ng the obvious thing to do is to switch back to zlib, since that would imply that zlib-ng is failing to compress adequately.

https://github.com/benkasminbullock/image-png-libpng/blob/7e24a30eb6ac5b1081399d3723f7e0f961e12b71/t/compress-level.t#L54

https://github.com/benkasminbullock/image-png-libpng/blob/7e24a30eb6ac5b1081399d3723f7e0f961e12b71/t/compress-level.t#L59
